# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andy_Lee's home page
url: "http://yourdomain.com" # the base hostname & protocol for your site

author: Andy_Lee
author_title: master student
email: 690312856@qq.com
department: School of Software Engineering
department_url: http://www.scut.edu.cn/sse
university: South China University of Technology
university_url: http://www.scut.edu.cn

paginate: 5
paginate_path: "blog/page:num"

baseurl:
pubs_path: /pubs
permalink: /:categories/:title
navigation:
    - title: Home
      link: /
    - title: Blog
      link: /blog
    - title: Projects
      link: /projects
    - title: Publications
      link: /publications.html
    - title: CV
      link: /cv.html


highlighter: true
markdown: redcarpet 
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

scholar:
  style: apa-no-doi-no-issue
  locale: en

  sort_by: none
  order: ascending

  repository: ./pubs
  source: /_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference }} {% if links.pdf %}<a href=\"{{ links.pdf }}\">PDF</a> {% endif %} "

  replace_strings: true
  join_strings:    true

  details_dir:    bibtex
  details_layout: bibtex.html
  details_link: BibTeX

  query: "@*"

